#!/usr/bin/env python3
import sys
import os

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
        # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets handle")
    tweetslist = get_user_timeline(sys.argv[1], 50)
    if tweetslist == None:
        sys.exit("Error to get tweets")
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    for tweet in tweetslist:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(" {} ".format(score)+"{}".format(tweet), "green"))
        elif score < 0.0:
            print(colored(" {} ".format(score)+"{}".format(tweet), "red"))
        else:
            print(colored(" {} ".format(score)+"{}".format(tweet), "yellow"))
        
if __name__ == "__main__":
    main()

